services:
  noob.expa_user_provider:
    class: NoobBundle\Security\ExpaUserProvider
    arguments: ["@session"]

  noob.expa_authenticator:
        class: NoobBundle\Security\ExpaAuthenticator
        arguments: ["@session", %simple_access_token%, %advanced_access_token%]

  noob.leadassignment:
        class: NoobBundle\Service\LeadAssignment
        arguments: []
