AIESECGermany\EntityBundle\Entity\AGBAgreement:
    relations:
        -
            rel: agb
            href:
                route: get_agb
                parameters:
                    agbID: expr(object.getAgb().getId())
        -
            rel: exchange
            href:
                route: get_peopleexchanges
                parameters:
                    agbID: expr(object.getExchange().getId())
    properties:
        agb:
            exclude: true
        exchange:
            exclude: true
