EntityBundle\Entity\StandardsAndSatisfaction:
	properties:
	  exchange:
		exclude: true
	virtual_properties:
		getExchangeId:
			serialized_name: exchangeId
			type: integer
		getPersonId:
			serialized_name: personId
			type: integer