persons:
    type:     rest
    resource: RESTBundle:People

agbs:
    type:     rest
    resource: RESTBundle:Agb

ops:
    type:     rest
    resource: RESTBundle:Ops

reintegration_activity:
    type:     rest
    resource: RESTBundle:ReintegrationActivity

reintegration_activity_participation:
    type:     rest
    resource: RESTBundle:ReintegrationActivityParticipation

lead_assignment:
    type:     rest
    resource: RESTBundle:Leadassignment