persons:
    type:     rest
    resource: RESTBundle:People

agbs:
    type:     rest
    resource: RESTBundle:Agb

agb_agreement:
    type:     rest
    resource: RESTBundle:AgbAgreement

exchanges:
    type:     rest
    resource: RESTBundle:Exchange

outgoer_preparation:
    type:     rest
    resource: RESTBundle:OutgoerPreparation

outgoer_preparation_participation:
    type:     rest
    resource: RESTBundle:OutgoerPreparationParticipation

online_outgoer_preparation_participation:
    type:     rest
    resource: RESTBundle:OnlineOutgoerPreparationParticipation

reintegration_activity:
    type:     rest
    resource: RESTBundle:ReintegrationActivity

reintegration_activity_participation:
    type:     rest
    resource: RESTBundle:ReintegrationActivityParticipation

lead_assignment:
    type:     rest
    resource: RESTBundle:Leadassignment

jds:
    type:     rest
    resource: RESTBundle:Jd

reports:
    type:     rest
    resource: RESTBundle:Reports