persons:
    type:     rest
    resource: RESTBundle:People

agbs:
    type:     rest
    resource: RESTBundle:Agb

ops:
    type:     rest
    resource: RESTBundle:Ops

whs:
    type:     rest
    resource: RESTBundle:Whs

lead_assignment:
    type:     rest
    resource: RESTBundle:Leadassignment