persons:
    type:     rest
    resource: RESTBundle:People

agbs:
    type:     rest
    resource: RESTBundle:Agb

agb_agreement:
    type:     rest
    resource: RESTBundle:AgbAgreement

outgoer_preparation:
    type:     rest
    resource: RESTBundle:OutgoerPreparation

outgoer_preparation_participation:
    type:     rest
    resource: RESTBundle:OutgoerPreparationParticipation

reintegration_activity:
    type:     rest
    resource: RESTBundle:ReintegrationActivity

reintegration_activity_participation:
    type:     rest
    resource: RESTBundle:ReintegrationActivityParticipation

lead_assignment:
    type:     rest
    resource: RESTBundle:Leadassignment

reports:
    type:     rest
    resource: RESTBundle:Reports